### ISSUE TITLE
Can't compile on CentOS 6.9

### ISSUE THREAD

**Issue by SviMik** [WuBingzheng/memleax#36]
OS:
CentOS release 6.9 (Final)

Steps to reproduce:
wget https://github.com/WuBingzheng/memleax/archive/v1.1.1.zip
unzip v1.1.1.zip && cd memleax-1.1.1
./configure && make && make install

Output:
checking machine type...
checking OS type...
checking libraries...
checking libunwind...
checking libelf...
checking libdw...
libdw-devel is missing.
checking libdwarf...
generate Makefile...
done.
cc -DMLX_X86_64 -DMLX_LINUX -DMLX_WITH_LIBDWARF -I/usr/include/libdwarf/ -g -O2 -Wall   -c -o breakpoint.o breakpoint.c
In file included from machines.h:4:0,
                 from breakpoint.c:15:
ptrace_utils.h: In function ‘ptrace_get_regs’:
ptrace_utils.h:35:9: error: ‘PTRACE_GETREGSET’ undeclared (first use in this function)
  ptrace(PTRACE_GETREGSET, pid, (void *)regset, &ioVec);
         ^
ptrace_utils.h:35:9: note: each undeclared identifier is reported only once for each function it appears in
ptrace_utils.h: In function ‘ptrace_set_regs’:
ptrace_utils.h:47:9: error: ‘PTRACE_SETREGSET’ undeclared (first use in this function)
  ptrace(PTRACE_SETREGSET, pid, (void *)regset, &ioVec);
         ^
make: *** [breakpoint.o] Error 1

**Comment by SviMik** [comment]
Note: the master branch gives the same error.

**Comment by WuBingzheng** [comment]
It seems that 'PTRACE_GETREGS' is not detected at ptrace_utils.h:ptrace_get_regs().
While the 'PTRACE_GETREGSET' is for FreeBSD.

I have not a CenOS 6.9 now. Would you like to check is there 'PTRACE_GETREGS' defined in <sys/ptrace.h> in your system? This file should be something like /usr/include/x86_64-linux-gnu/sys/ptrace.h .

**Comment by SviMik** [comment]
Attaching
/usr/include/sys/ptrace.h
/usr/include/linux/ptrace.h

[1] http://svimik.com/centos6_sys_ptrace.h
[2] http://svimik.com/centos6_linux_ptrace.h

**Comment by WuBingzheng** [comment]
I just find that `PTRACE_GETREGS` is defined as enum, but not macro, in `/usr/include/x86_64-linux-gnu/sys/ptrace.h`. So the `#ifdef PTRACE_GETREGS` in `memleax/ptrace_utils.h:ptrace_get_regs()` may not work as expected.

But I also find `PTRACE_GETREGS` __macro__ defined in `/usr/include/x86_64-linux-gnu/asm/ptrace-abi.h` at CentOS 7, so it works fine. Would you like to execute the command in your system to find any macro defined at CentOS 6:

    grep PTRACE_GETREGS -wr /usr/include

Besides, I fix this and post a patch here. Would you like apply this and re-try to build memleax again?


[memleax.bugfix-ptrace.patch.txt](https://github.com/WuBingzheng/memleax/files/2042014/memleax.bugfix-ptrace.patch.txt)

**Comment by SviMik** [comment]
>grep PTRACE_GETREGS -wr /usr/include
/usr/include/sys/ptrace.h:   PTRACE_GETREGS = 12,
/usr/include/sys/ptrace.h:#define PT_GETREGS PTRACE_GETREGS
/usr/include/asm/ptrace-abi.h:#define PTRACE_GETREGS            12

>Besides, I fix this and post a patch here. Would you like apply this and re-try to build memleax again?
Sure, will try it today.

**Comment by SviMik** [comment]
The patch works (though I had to apply it manually for memleax-1.1.1 release).

**Comment by WuBingzheng** [comment]
good. I will push it later.
Thanks.
